4332-DEBUG-15-Nov-22 23:23:37-Trying to establish db connection...
4332-DEBUG-15-Nov-22 23:23:37-# _do_auth(): user: mahotpal1
4332-DEBUG-15-Nov-22 23:23:37-# _do_auth(): self._auth_plugin: 
4332-DEBUG-15-Nov-22 23:23:37-# _do_auth(): user: mahotpal1
4332-DEBUG-15-Nov-22 23:23:37-# _do_auth(): password: Abc@12345
4332-INFO-15-Nov-22 23:23:37-package: mysql.connector.plugins
4332-INFO-15-Nov-22 23:23:37-plugin_name: caching_sha2_password
4332-INFO-15-Nov-22 23:23:37-AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
4332-DEBUG-15-Nov-22 23:23:37-new_auth_plugin: caching_sha2_password
4332-INFO-15-Nov-22 23:23:37-Database connection established!
2052-ERROR-16-Nov-22 00:21:33-Exception on /mysqlPostman [POST]
Traceback (most recent call last):
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Vishal\DatabaseManager\app.py", line 16, in execute_query_mysql
    result = mySql.create_table(tableName,query)
TypeError: create_table() missing 1 required positional argument: 'table_comps'
2052-INFO-16-Nov-22 00:21:33-127.0.0.1 - - [16/Nov/2022 00:21:33] "[35m[1mPOST /mysqlPostman HTTP/1.1[0m" 500 -
8508-INFO-16-Nov-22 00:23:36-Executing Create Table!!!!
8508-DEBUG-16-Nov-22 00:23:36-Trying to establish db connection...
8508-DEBUG-16-Nov-22 00:23:37-# _do_auth(): user: mahotpal1
8508-DEBUG-16-Nov-22 00:23:37-# _do_auth(): self._auth_plugin: 
8508-DEBUG-16-Nov-22 00:23:37-# _do_auth(): user: mahotpal1
8508-DEBUG-16-Nov-22 00:23:37-# _do_auth(): password: Abc@12345
8508-INFO-16-Nov-22 00:23:37-package: mysql.connector.plugins
8508-INFO-16-Nov-22 00:23:37-plugin_name: caching_sha2_password
8508-INFO-16-Nov-22 00:23:37-AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
8508-DEBUG-16-Nov-22 00:23:37-new_auth_plugin: caching_sha2_password
8508-INFO-16-Nov-22 00:23:37-Database connection established!
8508-ERROR-16-Nov-22 00:23:37-Exception on /mysqlPostman [POST]
Traceback (most recent call last):
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Vishal\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Vishal\DatabaseManager\app.py", line 26, in execute_query_mysql
    return jsonify(result+"\n"+obj1.__str__)
TypeError: can only concatenate str (not "method") to str
8508-INFO-16-Nov-22 00:23:37-127.0.0.1 - - [16/Nov/2022 00:23:37] "[35m[1mPOST /mysqlPostman HTTP/1.1[0m" 500 -
6100-INFO-16-Nov-22 00:24:34-Executing Create Table!!!!
6100-DEBUG-16-Nov-22 00:24:34-Trying to establish db connection...
6100-DEBUG-16-Nov-22 00:24:35-# _do_auth(): user: mahotpal1
6100-DEBUG-16-Nov-22 00:24:35-# _do_auth(): self._auth_plugin: 
6100-DEBUG-16-Nov-22 00:24:35-# _do_auth(): user: mahotpal1
6100-DEBUG-16-Nov-22 00:24:35-# _do_auth(): password: Abc@12345
6100-INFO-16-Nov-22 00:24:35-package: mysql.connector.plugins
6100-INFO-16-Nov-22 00:24:35-plugin_name: caching_sha2_password
6100-INFO-16-Nov-22 00:24:35-AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
6100-DEBUG-16-Nov-22 00:24:35-new_auth_plugin: caching_sha2_password
6100-INFO-16-Nov-22 00:24:35-Database connection established!
6100-WARNING-16-Nov-22 00:24:35-Please check query 
6100-ERROR-16-Nov-22 00:24:35-1050 (42S01): Table 'tableno21' already exists
6100-INFO-16-Nov-22 00:24:35-127.0.0.1 - - [16/Nov/2022 00:24:35] "POST /mysqlPostman HTTP/1.1" 200 -
6100-INFO-16-Nov-22 00:25:03-Executing Create Table!!!!
6100-DEBUG-16-Nov-22 00:25:03-Trying to establish db connection...
6100-DEBUG-16-Nov-22 00:25:03-# _do_auth(): user: mahotpal1
6100-DEBUG-16-Nov-22 00:25:03-# _do_auth(): self._auth_plugin: 
6100-DEBUG-16-Nov-22 00:25:03-# _do_auth(): user: mahotpal1
6100-DEBUG-16-Nov-22 00:25:03-# _do_auth(): password: Abc@12345
6100-DEBUG-16-Nov-22 00:25:03-new_auth_plugin: caching_sha2_password
6100-INFO-16-Nov-22 00:25:03-Database connection established!
6100-INFO-16-Nov-22 00:25:03-127.0.0.1 - - [16/Nov/2022 00:25:03] "POST /mysqlPostman HTTP/1.1" 200 -
6100-INFO-16-Nov-22 00:25:16-Executing Create Table!!!!
6100-DEBUG-16-Nov-22 00:25:16-Trying to establish db connection...
6100-DEBUG-16-Nov-22 00:25:16-# _do_auth(): user: mahotpal1
6100-DEBUG-16-Nov-22 00:25:16-# _do_auth(): self._auth_plugin: 
6100-DEBUG-16-Nov-22 00:25:16-# _do_auth(): user: mahotpal1
6100-DEBUG-16-Nov-22 00:25:16-# _do_auth(): password: Abc@12345
6100-DEBUG-16-Nov-22 00:25:16-new_auth_plugin: caching_sha2_password
6100-INFO-16-Nov-22 00:25:16-Database connection established!
6100-WARNING-16-Nov-22 00:25:16-Please check query 
6100-ERROR-16-Nov-22 00:25:16-1050 (42S01): Table 'tableno22' already exists
6100-INFO-16-Nov-22 00:25:16-127.0.0.1 - - [16/Nov/2022 00:25:16] "POST /mysqlPostman HTTP/1.1" 200 -
3828-INFO-16-Nov-22 00:25:51-Executing Create Table!!!!
3828-DEBUG-16-Nov-22 00:25:51-Trying to establish db connection...
3828-DEBUG-16-Nov-22 00:25:51-# _do_auth(): user: mahotpal1
3828-DEBUG-16-Nov-22 00:25:51-# _do_auth(): self._auth_plugin: 
3828-DEBUG-16-Nov-22 00:25:51-# _do_auth(): user: mahotpal1
3828-DEBUG-16-Nov-22 00:25:51-# _do_auth(): password: Abc@12345
3828-INFO-16-Nov-22 00:25:51-package: mysql.connector.plugins
3828-INFO-16-Nov-22 00:25:51-plugin_name: caching_sha2_password
3828-INFO-16-Nov-22 00:25:51-AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
3828-DEBUG-16-Nov-22 00:25:51-new_auth_plugin: caching_sha2_password
3828-INFO-16-Nov-22 00:25:51-Database connection established!
3828-WARNING-16-Nov-22 00:25:51-Please check query 
3828-ERROR-16-Nov-22 00:25:51-1050 (42S01): Table 'tableno22' already exists
3828-INFO-16-Nov-22 00:25:51-127.0.0.1 - - [16/Nov/2022 00:25:51] "POST /mysqlPostman HTTP/1.1" 200 -
3828-INFO-16-Nov-22 00:26:12-127.0.0.1 - - [16/Nov/2022 00:26:12] "[31m[1mPOST /mysqlPostman HTTP/1.1[0m" 400 -
3828-INFO-16-Nov-22 00:26:30-Executing Create Table!!!!
3828-DEBUG-16-Nov-22 00:26:30-Trying to establish db connection...
3828-DEBUG-16-Nov-22 00:26:30-# _do_auth(): user: mahotpal1
3828-DEBUG-16-Nov-22 00:26:30-# _do_auth(): self._auth_plugin: 
3828-DEBUG-16-Nov-22 00:26:30-# _do_auth(): user: mahotpal1
3828-DEBUG-16-Nov-22 00:26:30-# _do_auth(): password: Abc@12345
3828-DEBUG-16-Nov-22 00:26:30-new_auth_plugin: caching_sha2_password
3828-INFO-16-Nov-22 00:26:30-Database connection established!
3828-WARNING-16-Nov-22 00:26:30-Please check query 
3828-ERROR-16-Nov-22 00:26:30-1050 (42S01): Table 'tableno22' already exists
3828-INFO-16-Nov-22 00:26:30-127.0.0.1 - - [16/Nov/2022 00:26:30] "POST /mysqlPostman HTTP/1.1" 200 -
3828-INFO-16-Nov-22 00:28:50-127.0.0.1 - - [16/Nov/2022 00:28:50] "[31m[1mGET /mysqlPostman HTTP/1.1[0m" 405 -
3828-INFO-16-Nov-22 00:29:33-127.0.0.1 - - [16/Nov/2022 00:29:33] "[31m[1mGET /mysqlPostman HTTP/1.1[0m" 405 -
3828-INFO-16-Nov-22 00:30:08-Executing insertSingleData!!!!
3828-INFO-16-Nov-22 00:30:08-Database connection established!
3828-INFO-16-Nov-22 00:30:08-127.0.0.1 - - [16/Nov/2022 00:30:08] "POST /mysqlPostman HTTP/1.1" 200 -
4228-INFO-16-Nov-22 00:36:48-Executing bulk Insertion!!!
4228-INFO-16-Nov-22 00:36:48-Database Connection Established!!!
4228-ERROR-16-Nov-22 00:36:48-1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[' at line 1
4228-INFO-16-Nov-22 00:36:48-127.0.0.1 - - [16/Nov/2022 00:36:48] "POST /mysqlPostman HTTP/1.1" 200 -
4228-INFO-16-Nov-22 00:38:23-Executing bulk Insertion!!!
4228-INFO-16-Nov-22 00:38:23-Database Connection Established!!!
4228-ERROR-16-Nov-22 00:38:23-1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[' at line 1
4228-INFO-16-Nov-22 00:38:23-127.0.0.1 - - [16/Nov/2022 00:38:23] "POST /mysqlPostman HTTP/1.1" 200 -
4228-INFO-16-Nov-22 00:42:13-Executing bulk Insertion!!!
4228-INFO-16-Nov-22 00:42:13-Database Connection Established!!!
4228-INFO-16-Nov-22 00:42:14-127.0.0.1 - - [16/Nov/2022 00:42:14] "POST /mysqlPostman HTTP/1.1" 200 -
4228-INFO-16-Nov-22 00:44:38-Executing update Table!
4228-INFO-16-Nov-22 00:44:38-Database Connection Established!!!
4228-INFO-16-Nov-22 00:44:38-127.0.0.1 - - [16/Nov/2022 00:44:38] "POST /mysqlPostman HTTP/1.1" 200 -
